name: "[Workflow] On Source Change"

on:
  push:
    branches:
      - main
    paths:
      - 'ops/helm/**'

concurrency:
    group: push-${{ github.branch }}

jobs:
  determine-changed-charts:
    name: "Changed Charts"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/helm'

  validate:
    name: "Validate"
    needs: [ determine-changed-charts ]
    if: needs.determine-changed-charts.outputs.matrix != '[]'
    uses: webgrip/workflows/.github/workflows/helm-charts-validate.yml@main
    with:
      paths: ${{ needs.determine-changed-charts.outputs.matrix }}

  semantic-release:
    name: "Semantic Release"
    needs: [ validate ]
    if: needs.validate.result == 'success'
    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main

  push-charts:
    name: "Push"
    if: >
      always()
      && needs.semantic-release.result == 'success'
      && needs.semantic-release.outputs.version != ''
    needs: [ determine-changed-charts, semantic-release ]
    uses: webgrip/workflows/.github/workflows/helm-charts-push.yml@main
    with:
        paths: ${{ needs.determine-changed-charts.outputs.matrix }}
        version: ${{ needs.semantic-release.outputs.version }}
