name: "[Workflow] On Source Change"

on:
  push:
    branches:
      - main
    paths:
      - 'ops/helm/**'
      - '.github/workflows/on_source_change.yml'

concurrency:
    group: push-${{ github.branch }}

jobs:
  determine-changed-charts:
    name: "Secrets"
    uses: vendic/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/helm'

  validate:
    name: "Validate"
    needs: [ determine-changed-charts ]
    if: needs.determine-changed-charts.outputs.matrix != '[]'
    uses: ./.github/workflows/validate-helm-chart.yml
    with:
      path: ${{ needs.determine-changed-charts.outputs.matrix[0] }}

#  release:
#    name: 'Release'
#    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main
