name: "[Workflow] On Source Change"

on:
  push:
    branches:
      - main
    paths:
      - 'ops/helm/**'

concurrency:
    group: push-${{ github.branch }}

jobs:
  determine-changed-charts:
    name: "Changed Charts"
    uses: webgrip/workflows/.github/workflows/determine-changed-directories.yml@main
    with:
      inside-dir: 'ops/helm'

  validate:
    name: "Validate"
    needs: [ determine-changed-charts ]
    if: needs.determine-changed-charts.outputs.matrix != '[]'
    uses: webgrip/workflows/.github/workflows/validate-helm-charts.yml@main
    with:
      paths: ${{ needs.determine-changed-charts.outputs.matrix }}

#  release:
#    name: 'Release'
#    uses: webgrip/workflows/.github/workflows/semantic-release.yml@main
